### ISSUE TITLE
unable to get past "Running Migrations, please wait..."

### ISSUE THREAD

**Issue by Maverikms** [sandiz/rs-manager#135]
**Describe the bug**

**To Reproduce**
1. Launched RS Manager
2. get message "Running Migrations, please wait"
3. waited overnight, no success

**Expected behavior**

**Screenshots**

**Desktop (please complete the sfollowing information):**
 - OS: Windows 10, 64-bit
 - 
![image](https://user-images.githubusercontent.com/88512968/128420197-6f865779-1819-4fcb-9be5-7192eea27f8b.png)

 - Console Log/Screenshot (available via Edit -> Toggle Developer Tools -> Console)

**Additional context**

**Comment by sandiz** [comment]
sorry about the issue, can you pls share the logs generated (either copy paste or screenshot).. you can find them by going to 
Menu -> Edit -> Toggle Developer Tools -> Console tab.

**Comment by Rakshasas** [comment]
Hello sandiz,

Maverickms was borrowing my laptop at the time of his report. Here is the log from the console tab (username redacted)

init.ts:204 Unable to load preload script: C:\Users\*********\AppData\Local\Programs\Rocksmith Manager\resources\app\src\preload.js
(anonymous) @ init.ts:204
init.ts:205 Error: The specified module could not be found.
\\?\C:\Users\*********\AppData\Local\Programs\Rocksmith Manager\resources\app\node_modules\naudiodon\build\Release\naudiodon.node
    at process.func (electron/js2c/asar.js:140)
    at process.func [as dlopen] (electron/js2c/asar.js:140)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922)
    at Object.func (electron/js2c/asar.js:140)
    at Object.func [as .node] (electron/js2c/asar.js:140)
    at Module.load (internal/modules/cjs/loader.js:735)
    at Module._load (internal/modules/cjs/loader.js:648)
    at Module._load (electron/js2c/asar.js:717)
    at Function.Module._load (electron/js2c/asar.js:717)
    at Module.require (internal/modules/cjs/loader.js:775)
(anonymous) @ init.ts:205
index.js:23 appLocale: en-US
2configService.js:49 creating empty config file
Sidebar.js:130 checking for update...
configService.js:49 creating empty config file
3configService.js:62 Error: Could not call remote method 'writeFile'. Check that the method signature is correct. Underlying error: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
Underlying stack: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.open (fs.js:413:10)
    at Object.module.<computed> (electron/js2c/asar.js:163:31)
    at Object.module.<computed> [as open] (electron/js2c/asar.js:163:31)
    at Object.writeFile (fs.js:1184:6)
    at electron/js2c/browser_init.js:6626:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6479:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3850:23)
    at WebContents.emit (events.js:203:13)

    at electron/js2c/browser_init.js:6628:17
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6479:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3850:23)
    at WebContents.emit (events.js:203:13)
HelpView.js:91 Uncaught (in promise) TypeError: window.request is not a function
    at HelpView.js:91
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
    at u (runtime.js:45)
    at t (runtime.js:135)
    at runtime.js:170
    at new Promise (<anonymous>)
    at o (runtime.js:169)
    at k._invoke (runtime.js:192)
C:\Users\*********\AppData\Local\Programs\Rocksmith Manager\resources\app\node_modules\sqlite\main.js:484 Uncaught (in promise) TypeError: Argument 0 must be a string
    at Promise.then.db.driver (C:\Users\*********\AppData\Local\Programs\Rocksmith Manager\resources\app\node_modules\sqlite\main.js:484)
    at new Promise (<anonymous>)
    at Database.db.open (C:\Users\*********\AppData\Local\Programs\Rocksmith Manager\resources\app\node_modules\sqlite\main.js:474)
    at sqliteService.js:39
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
    at u (runtime.js:45)
    at t (runtime.js:135)
    at runtime.js:170
steamprofileService.js:267 Uncaught (in promise) TypeError: Cannot read property 'join' of undefined
    at steamprofileService.js:267
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
    at u (runtime.js:45)
    at t (runtime.js:135)
    at runtime.js:170
    at new Promise (<anonymous>)
    at o (runtime.js:169)
    at k._invoke (runtime.js:192)
index.js:14 language-changed Object
2HelpView.js:91 Uncaught (in promise) TypeError: window.request is not a function
    at HelpView.js:91
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
    at u (runtime.js:45)
    at t (runtime.js:135)
    at runtime.js:170
    at new Promise (<anonymous>)
    at o (runtime.js:169)
    at k._invoke (runtime.js:192)
(anonymous) @ HelpView.js:91
u @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
u @ runtime.js:45
t @ runtime.js:135
(anonymous) @ runtime.js:170
o @ runtime.js:169
_invoke @ runtime.js:192
forEach.e.<computed> @ runtime.js:97
e.async @ runtime.js:216
a.changeTo @ HelpView.js:58
(anonymous) @ HelpView.js:54
u @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
u @ runtime.js:45
t @ runtime.js:135
(anonymous) @ runtime.js:170
o @ runtime.js:169
_invoke @ runtime.js:192
forEach.e.<computed> @ runtime.js:97
e.async @ runtime.js:216
a.shouldComponentUpdate @ HelpView.js:52
Po @ react-dom.production.min.js:134
Ja @ react-dom.production.min.js:178
Ms @ react-dom.production.min.js:261
Al @ react-dom.production.min.js:230
Pl @ react-dom.production.min.js:229
_l @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Xi @ react-dom.production.min.js:120
Ji @ react-dom.production.min.js:121
$i @ react-dom.production.min.js:120
se @ react-dom.production.min.js:285
Cn @ react-dom.production.min.js:82
Show 7 more frames

**Comment by sandiz** [comment]
looks like a corrupt install or somehow the files were deleted (antivirus?)

can you try uninstall and reinstalling again using the [setup exe](https://github.com/sandiz/rs-manager/releases/download/v3.0.15/Rocksmith.Manager-3.0.15-win.exe) and whitelist the installation folder in your antivirus software (if you have any)
